version: 0.0
Resources:
  - TargetService:
    Type: AWS::ECS::Service
    Properties:
      TaskDefinition: $ECS_BLUE_TASK_DEFINITION
      LoadBalancerInfo:
        ContainerName: my-container
        ContainerPort: 8080
      PlatformVersion: LATEST
      NetworkConfiguration:
        AwsvpcConfiguration:
          Subnets:
            - $API_PRIVATE_SUBNET_A
            - $API_PRIVATE_SUBNET_C
          SecurityGroups:
            - $API_WAS_SECURITY_GROUP
          AssignPublicIp: ENABLED
hooks:
  BeforeInstall:
    - timeout: 300
      runas: root
      script: |
        #!/bin/bash
        aws ecs update-service --cluster Apollo-Server-Cluster --service Apollo-Server-Service --force-new-deployment
