AWSTemplateFormatVersion: "2010-09-09"
Description: resource for s3bucket
Resources:
  MyS3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: no-duplicated-bucket-name-with-apollo
      #acl 활성화
      AccessControl: Private
      PublicAccessBlockConfiguration:
        #퍼블릭 acl 액세스 차단
        BlockPublicAcls: false
        BlockPublicPolicy: false
        IgnorePublicAcls: false
        RestrictPublicBuckets: false
      WebsiteConfiguration:
        IndexDocument: index.html
