version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18

  pre_build:
    commands:
      - echo "Installing..."
      - npm install

  build:
    commands:
      - echo "building project..."
      - npm run build

  post_build:
    commands:
      - echo "uploading build artifact to S3..."
      - aws s3 sync build s3://apollo-client-bucket --delete
